import type {AuthLocalization} from "@daveyplate/better-auth-ui";

export const HebrewAuthErrors: Partial<AuthLocalization> = {
    INVALID_USERNAME_OR_PASSWORD: "שם משתמש או סיסמה לא נכונים",
    EMAIL_NOT_VERIFIED: "האימייל שלך לא אומת",
    UNEXPECTED_ERROR: "אירעה שגיאה בלתי צפויה",
    USERNAME_IS_ALREADY_TAKEN: "שם המשתמש כבר תפוס",
    USERNAME_TOO_SHORT: "שם המשתמש קצר מדי",
    USERNAME_TOO_LONG: "שם המשתמש ארוך מדי",
    INVALID_USERNAME: "שם משתמש לא תקין",
    INVALID_EMAIL: "אימייל לא תקין",
    USER_NOT_FOUND: "המשתמש לא נמצא",
    INVALID_PASSWORD: "סיסמה לא תקינה",
    INVALID_EMAIL_OR_PASSWORD: "אימייל או סיסמה לא נכונים",
    PASSWORD_TOO_SHORT: "הסיסמה קצרה מדי",
    PASSWORD_TOO_LONG: "הסיסמה ארוכה מדי",
    PASSWORD_COMPROMISED: "הסיסמה נמצאה כחשופה",
    TOO_MANY_ATTEMPTS: "יותר מדי ניסיונות, נסה שוב מאוחר יותר",
    SERVICE_UNAVAILABLE: "השירות אינו זמין כרגע",
    VERIFICATION_FAILED: "האימות נכשל",
    UNKNOWN_ERROR: "שגיאה לא ידועה",
};


export const HebrewUserAccount: Partial<AuthLocalization> = {
    SIGN_IN: "התחברות",
    SIGN_IN_ACTION: "התחבר",
    SIGN_IN_DESCRIPTION: "הזן את האימייל שלך כדי להתחבר לחשבון",
    SIGN_IN_USERNAME_DESCRIPTION: "הזן את שם המשתמש או האימייל שלך כדי להתחבר",
    SIGN_IN_WITH: "התחבר באמצעות",
    SIGN_OUT: "התנתק",
    SIGN_UP: "הרשמה",
    SIGN_UP_ACTION: "צור חשבון",
    SIGN_UP_DESCRIPTION: "הזן את הפרטים שלך כדי ליצור חשבון חדש",
    SIGN_UP_EMAIL: "בדוק את תיבת האימייל שלך לאימות ההרשמה",
    EMAIL: "אימייל",
    EMAIL_PLACEHOLDER: "m@example.com",
    EMAIL_REQUIRED: "כתובת אימייל נדרשת",
    OR_CONTINUE_WITH: 'או המשך עם',
    PASSWORD: "סיסמה",
    PASSWORD_PLACEHOLDER: "••••••••",
    PASSWORD_REQUIRED: "סיסמה נדרשת",
    CONFIRM_PASSWORD: "אישור סיסמה",
    CONFIRM_PASSWORD_PLACEHOLDER: "הזן שוב את הסיסמה",
    CONFIRM_PASSWORD_REQUIRED: "יש לאשר סיסמה",
    PASSWORDS_DO_NOT_MATCH: "הסיסמאות אינן תואמות",
    FORGOT_PASSWORD: "שכחת סיסמה?",
    FORGOT_PASSWORD_ACTION: "שלח קישור לאיפוס",
    FORGOT_PASSWORD_DESCRIPTION: "הזן את האימייל שלך כדי לאפס את הסיסמה",
    RESET_PASSWORD: "איפוס סיסמה",
    RESET_PASSWORD_ACTION: "שמור סיסמה חדשה",
    RESET_PASSWORD_DESCRIPTION: "הזן סיסמה חדשה למטה",
    RESET_PASSWORD_SUCCESS: "הסיסמה אופסה בהצלחה",
    SESSION_EXPIRED: "תוקף ההתחברות פג, אנא התחבר מחדש",
    DONT_HAVE_AN_ACCOUNT: 'אין לך חשבון?',
    FORGOT_PASSWORD_LINK: "שכחת את הסיסמה?",
    ALREADY_HAVE_AN_ACCOUNT: 'כבר יש לך חשבון?',
};

export const HebrewUI: Partial<AuthLocalization> = {
    CONTINUE: "המשך",
    CANCEL: "ביטול",
    SAVE: "שמור",
    DELETE: "מחק",
    UPDATED_SUCCESSFULLY: "עודכן בהצלחה",
    GO_BACK: "חזור",
    UNKNOWN: "לא ידוע",
    APP: "אפליקציה",
    ACCOUNT: "חשבון",
    SETTINGS: "הגדרות",
    SECURITY: "אבטחה",
    SESSION_NOT_FRESH: "ההתחברות אינה עדכנית, יש להתחבר מחדש",
    TRUST_DEVICE: "סמוך על מכשיר זה",
    REMEMBER_ME: "זכור אותי",
};

export const HebrewAccountLocalization: Partial<AuthLocalization> = {
    ACCOUNT: "חשבון",
    ACCOUNTS: "חשבונות",
    ACCOUNTS_DESCRIPTION: "נהל את החשבונות שבהם אתה מחובר כרגע.",
    ACCOUNTS_INSTRUCTIONS: "התחבר לחשבון נוסף.",
    ADD_ACCOUNT: "הוסף חשבון",
    AVATAR: "תמונת פרופיל",
    AVATAR_DESCRIPTION: "לחץ על התמונה כדי להעלות תמונה מותאמת אישית מהמחשב שלך.",
    AVATAR_INSTRUCTIONS: "תמונת פרופיל היא רשות אך מומלצת בחום.",
    CHANGE_PASSWORD: "שנה סיסמה",
    CHANGE_PASSWORD_DESCRIPTION: "הזן את הסיסמה הנוכחית וסיסמה חדשה.",
    CHANGE_PASSWORD_INSTRUCTIONS: "אנא השתמש בלפחות 8 תווים.",
    CHANGE_PASSWORD_SUCCESS: "הסיסמה שלך שונתה בהצלחה.",
    CONFIRM_PASSWORD: "אשר סיסמה",
    CONFIRM_PASSWORD_PLACEHOLDER: "הזן שוב את הסיסמה",
    CONFIRM_PASSWORD_REQUIRED: "חובה לאשר סיסמה",
    CURRENT_PASSWORD: "סיסמה נוכחית",
    CURRENT_PASSWORD_PLACEHOLDER: "הזן את הסיסמה הנוכחית שלך",
    DELETE_ACCOUNT: "מחק חשבון",
    DELETE_ACCOUNT_DESCRIPTION:
        "מחק לצמיתות את החשבון וכל תוכנו. פעולה זו אינה הפיכה, אנא המשך בזהירות.",
    DELETE_ACCOUNT_INSTRUCTIONS:
        "אנא אשר את מחיקת החשבון שלך. פעולה זו אינה הפיכה.",
    DELETE_ACCOUNT_VERIFY: "בדוק את האימייל שלך כדי לאשר את מחיקת החשבון.",
    DELETE_ACCOUNT_SUCCESS: "החשבון שלך נמחק בהצלחה.",
    DISABLE_TWO_FACTOR: "השבת אימות דו־שלבי",
    ENABLE_TWO_FACTOR: "הפעל אימות דו־שלבי",
    SET_PASSWORD: "קבע סיסמה",
    SET_PASSWORD_DESCRIPTION:
        "לחץ על הכפתור כדי לקבל מייל לקביעת סיסמה לחשבונך.",
    SETTINGS: "הגדרות",
    SECURITY: "אבטחה",
    UPDATED_SUCCESSFULLY: "החשבון עודכן בהצלחה",
    NAME: "שם",
    NAME_PLACEHOLDER: "הזן את שמך המלא",
    NAME_DESCRIPTION: 'אנא הזן את שמך המלא, או שם תצוגה.',
    EMAIL_DESCRIPTION: 'הזן את כתובת האימייל שבה ברצונך להשתמש כדי להתחבר.',
    INVALID_EMAIL: " כתובת אימייל לא תקינה",
    PROVIDERS: "ספקים",
    //Connect your account with a third-party service.
    PROVIDERS_DESCRIPTION: "נהל את חשבונך עם שירותי צד שלישי.",
    UNLINK: 'התנתק',
    SESSIONS: "התחברויות",
    SESSIONS_DESCRIPTION:
        "נהל את ההתחברויות הפעילות שלך. התנתק מההתקנים שבהם אינך משתמש יותר.",
    CURRENT_SESSION: "התחברות נוכחית",
};




export const HebrewAuthLocalization: AuthLocalization = {
    ...HebrewAuthErrors,
    ...HebrewUserAccount,
    ...HebrewUI,
    ...HebrewAccountLocalization,
};
